"""Add id_chamado_log to ChamadoLembrete

Revision ID: 05b12b07962d
Revises: ec668a9bcb9c
Create Date: 2026-01-21 00:37:34.642199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '05b12b07962d'
down_revision = 'ec668a9bcb9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamado_lembretes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_chamado_log', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'chamado_logs', ['id_chamado_log'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamado_lembretes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_chamado_log')

    op.create_table('import_clientes_backup',
    sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_cliente', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('before_row', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("action = 'UPDATE'::text", name=op.f('import_clientes_backup_action_check')),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.batch_id'], name=op.f('import_clientes_backup_batch_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('batch_id', 'id_cliente', name=op.f('import_clientes_backup_pkey'))
    )
    op.create_table('import_usinas_backup',
    sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_usina', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('before_row', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("action = 'UPDATE'::text", name=op.f('import_usinas_backup_action_check')),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.batch_id'], name=op.f('import_usinas_backup_batch_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('batch_id', 'id_usina', name=op.f('import_usinas_backup_pkey'))
    )
    op.create_table('import_inserts',
    sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('row_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("table_name = ANY (ARRAY['clientes'::text, 'usinas'::text])", name=op.f('import_inserts_table_name_check')),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.batch_id'], name=op.f('import_inserts_batch_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('batch_id', 'table_name', 'row_id', name=op.f('import_inserts_pkey'))
    )
    op.create_table('import_batches',
    sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_file', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('batch_id', name=op.f('import_batches_pkey'))
    )
    # ### end Alembic commands ###
