"""Add modalidade column

Revision ID: 0f8f289b7e50
Revises: ceb8f5cbbe63
Create Date: 2025-11-30 21:21:54.537991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8f289b7e50'
down_revision = 'ceb8f5cbbe63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modalidade', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcamentos', schema=None) as batch_op:
        batch_op.drop_column('modalidade')

    # ### end Alembic commands ###
