"""Adiciona campos de endereço detalhado a usinas

Revision ID: 0fba1da9d63e
Revises: bda8535a4f81
Create Date: 2025-10-21 23:26:43.930466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fba1da9d63e'
down_revision = 'bda8535a4f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usinas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logradouro', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bairro', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pais', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usinas', schema=None) as batch_op:
        batch_op.drop_column('cep')
        batch_op.drop_column('pais')
        batch_op.drop_column('estado')
        batch_op.drop_column('bairro')
        batch_op.drop_column('logradouro')

    # ### end Alembic commands ###
