"""Adiciona tabelas de Ordem de Serviço

Revision ID: 242865075256
Revises: 0fba1da9d63e
Create Date: 2025-11-11 01:09:39.679735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '242865075256'
down_revision = '0fba1da9d63e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordens_servico',
    sa.Column('id_orden_servico', sa.Integer(), nullable=False),
    sa.Column('id_orcamento', sa.Integer(), nullable=False),
    sa.Column('id_chamado', sa.Integer(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_usina', sa.Integer(), nullable=False),
    sa.Column('id_usuario_responsavel', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_chamado'], ['chamados.id_chamado'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_orcamento'], ['orcamentos.id_orcamento'], ),
    sa.ForeignKeyConstraint(['id_usina'], ['usinas.id_usina'], ),
    sa.ForeignKeyConstraint(['id_usuario_responsavel'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_orden_servico'),
    sa.UniqueConstraint('id_orcamento')
    )
    op.create_table('ordem_servico_itens',
    sa.Column('id_item_os', sa.Integer(), nullable=False),
    sa.Column('id_ordem_servico', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('concluido', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_ordem_servico'], ['ordens_servico.id_orden_servico'], ),
    sa.PrimaryKeyConstraint('id_item_os')
    )
    op.drop_table('orden_servico')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orden_servico',
    sa.Column('id_orden_servico', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_chamado_vinculado', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_orcamento_associado', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_usuario_responsavel', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_criacao', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('data_agendamento', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('data_conclusao', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('relatorio_tecnico', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_chamado_vinculado'], ['chamados.id_chamado'], name=op.f('orden_servico_id_chamado_vinculado_fkey')),
    sa.ForeignKeyConstraint(['id_orcamento_associado'], ['orcamentos.id_orcamento'], name=op.f('orden_servico_id_orcamento_associado_fkey')),
    sa.ForeignKeyConstraint(['id_usuario_responsavel'], ['usuarios.id_usuario'], name=op.f('orden_servico_id_usuario_responsavel_fkey')),
    sa.PrimaryKeyConstraint('id_orden_servico', name=op.f('orden_servico_pkey'))
    )
    op.drop_table('ordem_servico_itens')
    op.drop_table('ordens_servico')
    # ### end Alembic commands ###
