"""Corrige import circular de models e adiciona categorias

Revision ID: 2b0aec9cab50
Revises: 242865075256
Create Date: 2025-11-15 13:59:54.831295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b0aec9cab50'
down_revision = '242865075256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    '''
    op.drop_table('usuarios')
    op.drop_table('usinas')
    op.drop_table('chamado_logs')
    op.drop_table('inversores')
    op.drop_table('ordem_servico_itens')
    op.drop_table('orcamento_servicos')
    op.drop_table('chamados')
    op.drop_table('orcamentos')
    op.drop_table('materiais')
    op.drop_table('ordens_servico')
    op.drop_table('servicos')
    op.drop_table('orcamento_materiais')
    op.drop_table('clientes')
    '''
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    '''
    op.create_table('clientes',
    sa.Column('id_cliente', sa.INTEGER(), server_default=sa.text("nextval('clientes_id_cliente_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_cliente', name='clientes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('orcamento_materiais',
    sa.Column('id_orcamento_material', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_orcamento', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_material', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valor_unitario_cobrado', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_material'], ['materiais.id_material'], name=op.f('orcamento_materiais_id_material_fkey')),
    sa.ForeignKeyConstraint(['id_orcamento'], ['orcamentos.id_orcamento'], name=op.f('orcamento_materiais_id_orcamento_fkey')),
    sa.PrimaryKeyConstraint('id_orcamento_material', name=op.f('orcamento_materiais_pkey'))
    )
    op.create_table('servicos',
    sa.Column('id_servico', sa.INTEGER(), server_default=sa.text("nextval('servicos_id_servico_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome_servico', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('categoria_servico', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('valor_servico', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_servico', name='servicos_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('ordens_servico',
    sa.Column('id_orden_servico', sa.INTEGER(), server_default=sa.text("nextval('ordens_servico_id_orden_servico_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_orcamento', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_chamado', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_cliente', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_usina', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_usuario_responsavel', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('data_criacao', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('data_conclusao', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_chamado'], ['chamados.id_chamado'], name='ordens_servico_id_chamado_fkey'),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], name='ordens_servico_id_cliente_fkey'),
    sa.ForeignKeyConstraint(['id_orcamento'], ['orcamentos.id_orcamento'], name='ordens_servico_id_orcamento_fkey'),
    sa.ForeignKeyConstraint(['id_usina'], ['usinas.id_usina'], name='ordens_servico_id_usina_fkey'),
    sa.ForeignKeyConstraint(['id_usuario_responsavel'], ['usuarios.id_usuario'], name='ordens_servico_id_usuario_responsavel_fkey'),
    sa.PrimaryKeyConstraint('id_orden_servico', name='ordens_servico_pkey'),
    sa.UniqueConstraint('id_orcamento', name='ordens_servico_id_orcamento_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('materiais',
    sa.Column('id_material', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome_material', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('unidades', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('valor_custo', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('valor_venda', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_material', name=op.f('materiais_pkey'))
    )
    op.create_table('orcamentos',
    sa.Column('id_orcamento', sa.INTEGER(), server_default=sa.text("nextval('orcamentos_id_orcamento_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_chamado', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_usina', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_cliente', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_usuario_responsavel', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_criacao', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('descricao_servico', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('data_validade', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('valor_total_itens', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('desconto', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('valor_deslocamento', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('valor_total_final', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_chamado'], ['chamados.id_chamado'], name='orcamentos_id_chamado_fkey'),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], name='orcamentos_id_cliente_fkey'),
    sa.ForeignKeyConstraint(['id_usina'], ['usinas.id_usina'], name='orcamentos_id_usina_fkey'),
    sa.ForeignKeyConstraint(['id_usuario_responsavel'], ['usuarios.id_usuario'], name='orcamentos_id_usuario_responsavel_fkey'),
    sa.PrimaryKeyConstraint('id_orcamento', name='orcamentos_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('chamados',
    sa.Column('id_chamado', sa.INTEGER(), server_default=sa.text("nextval('chamados_id_chamado_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_usuario_responsavel', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_cliente', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_usina', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('prioridade', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('data_criacao', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('data_atualizacao', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'Aberto'::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], name='chamados_id_cliente_fkey'),
    sa.ForeignKeyConstraint(['id_usina'], ['usinas.id_usina'], name='chamados_id_usina_fkey'),
    sa.ForeignKeyConstraint(['id_usuario_responsavel'], ['usuarios.id_usuario'], name='chamados_id_usuario_responsavel_fkey'),
    sa.PrimaryKeyConstraint('id_chamado', name='chamados_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('orcamento_servicos',
    sa.Column('id_orcamento_servico', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_orcamento', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_servico', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valor_cobrado', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_orcamento'], ['orcamentos.id_orcamento'], name=op.f('orcamento_servicos_id_orcamento_fkey')),
    sa.ForeignKeyConstraint(['id_servico'], ['servicos.id_servico'], name=op.f('orcamento_servicos_id_servico_fkey')),
    sa.PrimaryKeyConstraint('id_orcamento_servico', name=op.f('orcamento_servicos_pkey'))
    )
    op.create_table('ordem_servico_itens',
    sa.Column('id_item_os', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_ordem_servico', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('concluido', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_ordem_servico'], ['ordens_servico.id_orden_servico'], name=op.f('ordem_servico_itens_id_ordem_servico_fkey')),
    sa.PrimaryKeyConstraint('id_item_os', name=op.f('ordem_servico_itens_pkey'))
    )
    op.create_table('inversores',
    sa.Column('id_inversor', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('marca', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('modelo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('potencia', sa.NUMERIC(precision=7, scale=2), autoincrement=False, nullable=True),
    sa.Column('disponivel', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('valor_aluguel', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_inversor', name=op.f('inversores_pkey'))
    )
    op.create_table('chamado_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_chamado', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('campo_alterado', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('valor_antigo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('valor_novo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tipo_log', sa.VARCHAR(length=20), server_default=sa.text("'automatico'::character varying"), autoincrement=False, nullable=False),
    sa.Column('comentario', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_chamado'], ['chamados.id_chamado'], name=op.f('chamado_logs_id_chamado_fkey')),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name=op.f('chamado_logs_id_usuario_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chamado_logs_pkey'))
    )
    op.create_table('usinas',
    sa.Column('id_usina', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome_usina', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cidade', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('id_cliente', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('logradouro', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bairro', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('pais', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cep', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], name=op.f('usinas_id_cliente_fkey')),
    sa.PrimaryKeyConstraint('id_usina', name=op.f('usinas_pkey'))
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome_usuario', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('nivel', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('avatar_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('theme_preference', sa.VARCHAR(length=10), server_default=sa.text("'system'::character varying"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_usuario', name=op.f('usuarios_pkey')),
    sa.UniqueConstraint('email', name=op.f('usuarios_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    '''
    pass
    # ### end Alembic commands ###
