"""Adiciona tabela chamado_anexos

Revision ID: 2c25ac18574b
Revises: b5ef5b9a6e42
Create Date: 2025-12-29 12:59:13.291303

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c25ac18574b'
down_revision = 'b5ef5b9a6e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chamado_anexos',
    sa.Column('id_anexo', sa.Integer(), nullable=False),
    sa.Column('id_chamado', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_log', sa.Integer(), nullable=True),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('tamanho_bytes', sa.BigInteger(), nullable=True),
    sa.Column('data_upload', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_chamado'], ['chamados.id_chamado'], ),
    sa.ForeignKeyConstraint(['id_log'], ['chamado_logs.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_anexo')
    )
    # (Bloco removido)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usinas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usinas_cliente_id_solarz'))
        batch_op.create_index(batch_op.f('ux_usinas_cliente_uc'), ['id_cliente', 'uc'], unique=True, postgresql_where='(uc IS NOT NULL)')
        batch_op.create_index(batch_op.f('ix_usina_cliente_id_solarz'), ['cliente_id_solarz'], unique=False)
        batch_op.alter_column('dados_planilha',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('clientes_acessos_solarz', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_acessos_solarz_data_ref'))
        batch_op.drop_index(batch_op.f('ix_clientes_acessos_solarz_cliente_id_solarz'))
        batch_op.create_unique_constraint(batch_op.f('uq_cliente_data'), ['cliente_id_solarz', 'data_ref'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_ca_cliente_data'), ['cliente_id_solarz', 'data_ref'], unique=False)

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('dados_planilha',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    op.create_table('import_inserts',
    sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('row_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("table_name = ANY (ARRAY['clientes'::text, 'usinas'::text])", name=op.f('import_inserts_table_name_check')),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.batch_id'], name=op.f('import_inserts_batch_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('batch_id', 'table_name', 'row_id', name=op.f('import_inserts_pkey'))
    )
    op.create_table('import_batches',
    sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_file', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('batch_id', name='import_batches_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('import_clientes_backup',
    sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_cliente', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('before_row', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("action = 'UPDATE'::text", name=op.f('import_clientes_backup_action_check')),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.batch_id'], name=op.f('import_clientes_backup_batch_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('batch_id', 'id_cliente', name=op.f('import_clientes_backup_pkey'))
    )
    op.create_table('import_usinas_backup',
    sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_usina', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('before_row', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("action = 'UPDATE'::text", name=op.f('import_usinas_backup_action_check')),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.batch_id'], name=op.f('import_usinas_backup_batch_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('batch_id', 'id_usina', name=op.f('import_usinas_backup_pkey'))
    )
    op.drop_table('chamado_anexos')
    # ### end Alembic commands ###
