"""Adiciona soft delete (is_active) a chamados

Revision ID: 4b91b1f886ed
Revises: df3158678b7b
Create Date: 2025-10-19 00:58:24.932395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b91b1f886ed'
down_revision = 'df3158678b7b'
branch_labels = None
depends_on = None


def upgrade():
    # Dentro do novo arquivo de migração -> upgrade()
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='t'))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
