"""Cria tabela ChamadoLog para auditoria

Revision ID: 640221837e7a
Revises: 4b91b1f886ed
Create Date: 2025-10-19 11:23:29.046602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640221837e7a'
down_revision = '4b91b1f886ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chamado_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_chamado', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('campo_alterado', sa.String(length=50), nullable=False),
    sa.Column('valor_antigo', sa.Text(), nullable=True),
    sa.Column('valor_novo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_chamado'], ['chamados.id_chamado'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chamado_logs')
    # ### end Alembic commands ###
