"""add_scheduling_and_execution_models

Revision ID: 7f41b92d8649
Revises: b13b5bf064f4
Create Date: 2026-02-21 19:34:54.985776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f41b92d8649'
down_revision = 'b13b5bf064f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planning_week',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('unplanned_os_ids', sa.JSON(), nullable=False),
    sa.Column('unplanned_reasons', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['technician_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start_date', 'technician_id', name='uq_planning_week_date_tech')
    )
    op.create_table('planning_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('total_travel_min', sa.Float(), nullable=True),
    sa.Column('total_service_min', sa.Float(), nullable=True),
    sa.Column('total_day_min', sa.Float(), nullable=True),
    sa.Column('total_km', sa.Float(), nullable=True),
    sa.Column('eta_end_min', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['planning_week.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technician_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('plan_day_id', sa.Integer(), nullable=True),
    sa.Column('base_lat', sa.Float(), nullable=True),
    sa.Column('base_lng', sa.Float(), nullable=True),
    sa.Column('work_start_admin', sa.Time(), nullable=False),
    sa.Column('work_end_admin', sa.Time(), nullable=False),
    sa.Column('soft_limit_end', sa.Time(), nullable=False),
    sa.Column('default_lunch_duration_min', sa.Integer(), nullable=False),
    sa.Column('lunch_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lunch_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allow_overtime_today', sa.Boolean(), nullable=False),
    sa.Column('max_overtime_end', sa.Time(), nullable=False),
    sa.Column('current_os_id', sa.Integer(), nullable=True),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lng', sa.Float(), nullable=True),
    sa.Column('derived_timeline', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['current_os_id'], ['chamados.id_chamado'], ),
    sa.ForeignKeyConstraint(['plan_day_id'], ['planning_day.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'technician_id', name='uq_execution_day_date_tech')
    )
    op.create_table('planning_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('os_id', sa.Integer(), nullable=True),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('planned_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_service_min', sa.Integer(), nullable=True),
    sa.Column('planned_travel_min_from_prev', sa.Float(), nullable=True),
    sa.Column('planned_km_from_prev', sa.Float(), nullable=True),
    sa.Column('is_lunch_block', sa.Boolean(), nullable=False),
    sa.Column('is_return_continuation', sa.Boolean(), nullable=False),
    sa.Column('commitment_level', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['planning_day.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['os_id'], ['chamados.id_chamado'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_day_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('os_id', sa.Integer(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_min', sa.Integer(), nullable=True),
    sa.Column('remaining_work_min', sa.Integer(), nullable=True),
    sa.Column('allow_overtime', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['execution_day_id'], ['execution_day.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['os_id'], ['chamados.id_chamado'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commitment_level', sa.String(length=20),
                                       nullable=False, server_default='FLEXIVEL'))
        batch_op.add_column(sa.Column('time_window_start', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('time_window_end', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('status_execucao', sa.String(length=30),
                                       nullable=False, server_default='NAO_INICIADA'))
        batch_op.add_column(sa.Column('tempo_real_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('remaining_work_min', sa.Integer(), nullable=True))
        batch_op.alter_column('km_estimado',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.alter_column('km_estimado',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.drop_column('remaining_work_min')
        batch_op.drop_column('tempo_real_min')
        batch_op.drop_column('status_execucao')
        batch_op.drop_column('time_window_end')
        batch_op.drop_column('time_window_start')
        batch_op.drop_column('commitment_level')
    op.drop_table('execution_events')
    op.drop_table('planning_items')
    op.drop_table('execution_day')
    op.drop_table('planning_day')
    op.drop_table('planning_week')
    # ### end Alembic commands ###
