"""Add data_agendamento to Chamado

Revision ID: 83c7a98ae629
Revises: 0f8f289b7e50
Create Date: 2025-12-21 11:48:46.633130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c7a98ae629'
down_revision = '0f8f289b7e50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inversores')
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_agendamento', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('telefone')

    with op.batch_alter_table('materiais', schema=None) as batch_op:
        batch_op.alter_column('valor_venda',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.create_unique_constraint(None, ['nome_material'])
        batch_op.drop_column('unidades')
        batch_op.drop_column('valor_custo')

    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nome_servico'])
        batch_op.drop_column('categoria_servico')

    with op.batch_alter_table('usinas', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('pais',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usinas', schema=None) as batch_op:
        batch_op.alter_column('pais',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('estado',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_servico', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('materiais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_custo', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('unidades', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('valor_venda',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.drop_column('data_agendamento')

    op.create_table('inversores',
    sa.Column('id_inversor', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('marca', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('modelo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('potencia', sa.NUMERIC(precision=7, scale=2), autoincrement=False, nullable=True),
    sa.Column('disponivel', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('valor_aluguel', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_inversor', name=op.f('inversores_pkey'))
    )
    # ### end Alembic commands ###
