"""Criação inicial de todas as tabelas

Revision ID: 8bc9a18d8bfb
Revises: 
Create Date: 2025-10-16 07:08:47.523264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc9a18d8bfb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_table('inversores',
    sa.Column('id_inversor', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('potencia', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('disponivel', sa.Boolean(), nullable=True),
    sa.Column('valor_aluguel', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id_inversor')
    )
    op.create_table('materiais',
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('nome_material', sa.String(length=255), nullable=False),
    sa.Column('unidades', sa.String(length=50), nullable=True),
    sa.Column('valor_custo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_venda', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id_material')
    )
    op.create_table('servicos',
    sa.Column('id_servico', sa.Integer(), nullable=False),
    sa.Column('nome_servico', sa.String(length=255), nullable=False),
    sa.Column('categoria_servico', sa.String(length=100), nullable=False),
    sa.Column('valor_servico', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id_servico')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome_usuario', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('nivel', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('usinas',
    sa.Column('id_usina', sa.Integer(), nullable=False),
    sa.Column('nome_usina', sa.String(length=255), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=False),
    sa.Column('longitude', sa.String(length=50), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_usina')
    )
    op.create_table('chamados',
    sa.Column('id_chamado', sa.Integer(), nullable=False),
    sa.Column('id_usuario_responsavel', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_usina', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('prioridade', sa.String(length=50), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_usina'], ['usinas.id_usina'], ),
    sa.ForeignKeyConstraint(['id_usuario_responsavel'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_chamado')
    )
    op.create_table('orcamentos',
    sa.Column('id_orcamento', sa.Integer(), nullable=False),
    sa.Column('id_chamado', sa.Integer(), nullable=True),
    sa.Column('id_usina', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_usuario_responsavel', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('descricao_servico', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data_validade', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valor_total_itens', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_deslocamento', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_total_final', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_chamado'], ['chamados.id_chamado'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_usina'], ['usinas.id_usina'], ),
    sa.ForeignKeyConstraint(['id_usuario_responsavel'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_orcamento')
    )
    op.create_table('orcamento_materiais',
    sa.Column('id_orcamento_material', sa.Integer(), nullable=False),
    sa.Column('id_orcamento', sa.Integer(), nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario_cobrado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_material'], ['materiais.id_material'], ),
    sa.ForeignKeyConstraint(['id_orcamento'], ['orcamentos.id_orcamento'], ),
    sa.PrimaryKeyConstraint('id_orcamento_material')
    )
    op.create_table('orcamento_servicos',
    sa.Column('id_orcamento_servico', sa.Integer(), nullable=False),
    sa.Column('id_orcamento', sa.Integer(), nullable=False),
    sa.Column('id_servico', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_cobrado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_orcamento'], ['orcamentos.id_orcamento'], ),
    sa.ForeignKeyConstraint(['id_servico'], ['servicos.id_servico'], ),
    sa.PrimaryKeyConstraint('id_orcamento_servico')
    )
    op.create_table('orden_servico',
    sa.Column('id_orden_servico', sa.Integer(), nullable=False),
    sa.Column('id_chamado_vinculado', sa.Integer(), nullable=False),
    sa.Column('id_orcamento_associado', sa.Integer(), nullable=False),
    sa.Column('id_usuario_responsavel', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_agendamento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('relatorio_tecnico', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_chamado_vinculado'], ['chamados.id_chamado'], ),
    sa.ForeignKeyConstraint(['id_orcamento_associado'], ['orcamentos.id_orcamento'], ),
    sa.ForeignKeyConstraint(['id_usuario_responsavel'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_orden_servico')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orden_servico')
    op.drop_table('orcamento_servicos')
    op.drop_table('orcamento_materiais')
    op.drop_table('orcamentos')
    op.drop_table('chamados')
    op.drop_table('usinas')
    op.drop_table('usuarios')
    op.drop_table('servicos')
    op.drop_table('materiais')
    op.drop_table('inversores')
    op.drop_table('clientes')
    # ### end Alembic commands ###
