"""Make_id_orcamento_nullable

Revision ID: b5ef5b9a6e42
Revises: 83c7a98ae629
Create Date: 2025-12-22 12:57:56.050272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ef5b9a6e42'
down_revision = '83c7a98ae629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.alter_column('id_orcamento',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.alter_column('id_orcamento',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
