"""Adiciona tipo_log e comentario a ChamadoLog

Revision ID: bda8535a4f81
Revises: 640221837e7a
Create Date: 2025-10-19 15:30:02.503527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda8535a4f81'
down_revision = '640221837e7a'
branch_labels = None
depends_on = None


# Dentro do novo arquivo de migração -> upgrade()
# Dentro do novo arquivo de migração -> upgrade()
def upgrade():
    with op.batch_alter_table('chamado_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_log', sa.String(length=20), nullable=False, server_default='automatico'))
        batch_op.add_column(sa.Column('comentario', sa.Text(), nullable=True))
        # Torna colunas antigas opcionais
        batch_op.alter_column('campo_alterado', existing_type=sa.VARCHAR(length=50), nullable=True)

    # Atualiza os dados existentes
    op.execute("UPDATE chamado_logs SET tipo_log = 'automatico' WHERE tipo_log IS NULL")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamado_logs', schema=None) as batch_op:
        batch_op.alter_column('campo_alterado',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('comentario')
        batch_op.drop_column('tipo_log')

    # ### end Alembic commands ###
