"""Adiciona status a chamados

Revision ID: c3fa9f10b77a
Revises: 8bc9a18d8bfb
Create Date: 2025-10-17 12:47:10.497566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3fa9f10b77a'
down_revision = '8bc9a18d8bfb'
branch_labels = None
depends_on = None


def upgrade():
    # Dentro de migrations/versions/xxxx_adiciona_status_a_chamados.py -> upgrade()

    with op.batch_alter_table('chamados', schema=None) as batch_op:
        # --- CORREÇÃO APLICADA AQUI ---
        # Adicionamos server_default='Aberto'
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='Aberto')) 

# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
