"""Adiciona preferencia de tema ao usuario

Revision ID: df3158678b7b
Revises: c88c1a3263b0
Create Date: 2025-10-18 17:59:35.479681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df3158678b7b'
down_revision = 'c88c1a3263b0'
branch_labels = None
depends_on = None


# Dentro do novo arquivo de migração (ex: ..._adiciona_preferencia.py)

def upgrade():
    # ...
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        # Garanta que nullable=True esteja aqui
        batch_op.add_column(sa.Column('theme_preference', sa.String(length=10), nullable=True, server_default='system'))
    # ...


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('theme_preference')

    # ### end Alembic commands ###
