"""Add ChamadoLembrete table

Revision ID: ec668a9bcb9c
Revises: 2c25ac18574b
Create Date: 2026-01-21 00:08:30.841361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec668a9bcb9c'
down_revision = '2c25ac18574b'
branch_labels = None
depends_on = None


def _has_table(inspector, table_name):
    return table_name in inspector.get_table_names()


def _has_column(inspector, table_name, column_name):
    if not _has_table(inspector, table_name):
        return False
    return any(col["name"] == column_name for col in inspector.get_columns(table_name))


def _has_index(inspector, table_name, index_name):
    if not _has_table(inspector, table_name):
        return False
    return any(idx["name"] == index_name for idx in inspector.get_indexes(table_name))


def _has_unique_constraint(inspector, table_name, constraint_name):
    if not _has_table(inspector, table_name):
        return False
    return any(cst["name"] == constraint_name for cst in inspector.get_unique_constraints(table_name))


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    op.create_table('chamado_lembretes',
    sa.Column('id_lembrete', sa.Integer(), nullable=False),
    sa.Column('id_chamado', sa.Integer(), nullable=False),
    sa.Column('id_usuario_criador', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('data_lembrete', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_chamado'], ['chamados.id_chamado'], ),
    sa.ForeignKeyConstraint(['id_usuario_criador'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_lembrete')
    )

    if _has_column(inspector, 'clientes', 'dados_planilha'):
        with op.batch_alter_table('clientes', schema=None) as batch_op:
            batch_op.alter_column(
                'dados_planilha',
                existing_type=postgresql.JSONB(astext_type=sa.Text()),
                type_=sa.JSON(),
                existing_nullable=True
            )

    if _has_table(inspector, 'clientes_acessos_solarz'):
        old_idx = op.f('ix_ca_cliente_data')
        old_uq = op.f('uq_cliente_data')
        new_idx_cliente = op.f('ix_clientes_acessos_solarz_cliente_id_solarz')
        new_idx_data = op.f('ix_clientes_acessos_solarz_data_ref')

        with op.batch_alter_table('clientes_acessos_solarz', schema=None) as batch_op:
            if _has_index(inspector, 'clientes_acessos_solarz', old_idx):
                batch_op.drop_index(old_idx)
            if _has_unique_constraint(inspector, 'clientes_acessos_solarz', old_uq):
                batch_op.drop_constraint(old_uq, type_='unique')
            if not _has_index(inspector, 'clientes_acessos_solarz', new_idx_cliente):
                batch_op.create_index(new_idx_cliente, ['cliente_id_solarz'], unique=False)
            if not _has_index(inspector, 'clientes_acessos_solarz', new_idx_data):
                batch_op.create_index(new_idx_data, ['data_ref'], unique=False)

    if _has_table(inspector, 'usinas'):
        old_idx_solarz = op.f('ix_usina_cliente_id_solarz')
        old_idx_uc = op.f('ux_usinas_cliente_uc')
        new_idx_solarz = op.f('ix_usinas_cliente_id_solarz')
        has_cliente_id_solarz = _has_column(inspector, 'usinas', 'cliente_id_solarz')

        with op.batch_alter_table('usinas', schema=None) as batch_op:
            if _has_column(inspector, 'usinas', 'dados_planilha'):
                batch_op.alter_column(
                    'dados_planilha',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    type_=sa.JSON(),
                    existing_nullable=True
                )
            if _has_index(inspector, 'usinas', old_idx_solarz):
                batch_op.drop_index(old_idx_solarz)
            if _has_index(inspector, 'usinas', old_idx_uc):
                batch_op.drop_index(old_idx_uc, postgresql_where='(uc IS NOT NULL)')
            if not has_cliente_id_solarz:
                batch_op.add_column(sa.Column('cliente_id_solarz', sa.BigInteger(), nullable=True))
            if not _has_index(inspector, 'usinas', new_idx_solarz):
                batch_op.create_index(new_idx_solarz, ['cliente_id_solarz'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if _has_table(inspector, 'usinas'):
        new_idx_solarz = op.f('ix_usinas_cliente_id_solarz')
        old_idx_uc = op.f('ux_usinas_cliente_uc')
        old_idx_solarz = op.f('ix_usina_cliente_id_solarz')
        has_cliente_id_solarz = _has_column(inspector, 'usinas', 'cliente_id_solarz')
        has_uc = _has_column(inspector, 'usinas', 'uc')

        with op.batch_alter_table('usinas', schema=None) as batch_op:
            if _has_index(inspector, 'usinas', new_idx_solarz):
                batch_op.drop_index(new_idx_solarz)
            if _has_index(inspector, 'usinas', old_idx_solarz):
                batch_op.drop_index(old_idx_solarz)
            if has_uc and not _has_index(inspector, 'usinas', old_idx_uc):
                batch_op.create_index(old_idx_uc, ['id_cliente', 'uc'], unique=True, postgresql_where='(uc IS NOT NULL)')
            if _has_column(inspector, 'usinas', 'dados_planilha'):
                batch_op.alter_column(
                    'dados_planilha',
                    existing_type=sa.JSON(),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True
                )
            if has_cliente_id_solarz:
                batch_op.drop_column('cliente_id_solarz')

    if _has_table(inspector, 'clientes_acessos_solarz'):
        new_idx_data = op.f('ix_clientes_acessos_solarz_data_ref')
        new_idx_cliente = op.f('ix_clientes_acessos_solarz_cliente_id_solarz')
        old_uq = op.f('uq_cliente_data')
        old_idx = op.f('ix_ca_cliente_data')

        with op.batch_alter_table('clientes_acessos_solarz', schema=None) as batch_op:
            if _has_index(inspector, 'clientes_acessos_solarz', new_idx_data):
                batch_op.drop_index(new_idx_data)
            if _has_index(inspector, 'clientes_acessos_solarz', new_idx_cliente):
                batch_op.drop_index(new_idx_cliente)
            if not _has_unique_constraint(inspector, 'clientes_acessos_solarz', old_uq):
                batch_op.create_unique_constraint(old_uq, ['cliente_id_solarz', 'data_ref'], postgresql_nulls_not_distinct=False)
            if not _has_index(inspector, 'clientes_acessos_solarz', old_idx):
                batch_op.create_index(old_idx, ['cliente_id_solarz', 'data_ref'], unique=False)

    if _has_column(inspector, 'clientes', 'dados_planilha'):
        with op.batch_alter_table('clientes', schema=None) as batch_op:
            batch_op.alter_column(
                'dados_planilha',
                existing_type=sa.JSON(),
                type_=postgresql.JSONB(astext_type=sa.Text()),
                existing_nullable=True
            )

    op.create_table('import_usinas_backup',
    sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_usina', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('before_row', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("action = 'UPDATE'::text", name=op.f('import_usinas_backup_action_check')),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.batch_id'], name=op.f('import_usinas_backup_batch_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('batch_id', 'id_usina', name=op.f('import_usinas_backup_pkey'))
    )
    op.create_table('import_batches',
    sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_file', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('batch_id', name='import_batches_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('import_clientes_backup',
    sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_cliente', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('before_row', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("action = 'UPDATE'::text", name=op.f('import_clientes_backup_action_check')),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.batch_id'], name=op.f('import_clientes_backup_batch_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('batch_id', 'id_cliente', name=op.f('import_clientes_backup_pkey'))
    )
    op.create_table('import_inserts',
    sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('row_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("table_name = ANY (ARRAY['clientes'::text, 'usinas'::text])", name=op.f('import_inserts_table_name_check')),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.batch_id'], name=op.f('import_inserts_batch_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('batch_id', 'table_name', 'row_id', name=op.f('import_inserts_pkey'))
    )
    if _has_table(inspector, 'chamado_lembretes'):
        op.drop_table('chamado_lembretes')
    # ### end Alembic commands ###
